# Generated by Django 5.1.2 on 2026-10-08 18:59

from django.db import migrations, models


def normalize_user_choices(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    profile_model = apps.get_model("users", "UserProfile")

    user_type_mapping = {
        "ADMIN": "admin",
        "CLIENT": "client",
        "MASTER": "master",
    }
    gender_mapping = {
        "MALE": "male",
        "FEMALE": "female",
    }

    for old_value, new_value in user_type_mapping.items():
        user_model.objects.filter(user_type=old_value).update(user_type=new_value)
    for old_value, new_value in gender_mapping.items():
        profile_model.objects.filter(gender=old_value).update(gender=new_value)


def denormalize_user_choices(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    profile_model = apps.get_model("users", "UserProfile")

    user_type_mapping = {
        "admin": "ADMIN",
        "client": "CLIENT",
        "master": "MASTER",
    }
    gender_mapping = {
        "male": "MALE",
        "female": "FEMALE",
    }

    for old_value, new_value in user_type_mapping.items():
        user_model.objects.filter(user_type=old_value).update(user_type=new_value)
    for old_value, new_value in gender_mapping.items():
        profile_model.objects.filter(gender=old_value).update(gender=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_user_choices, denormalize_user_choices),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('master', 'Master')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
