# Generated by Django 5.1.2 on 2026-10-08 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'MASTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='masters.masterprofile'),
        ),
        migrations.AddField(
            model_name='masterservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_services', to='masters.servicecategory'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['is_available'], name='masters_mas_is_avai_2d3ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['city'], name='masters_mas_city_c875cf_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['rating'], name='masters_mas_rating_93f007_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['created_at'], name='masters_mas_created_2a2323_idx'),
        ),
        migrations.AddIndex(
            model_name='masterservice',
            index=models.Index(fields=['is_active'], name='masters_mas_is_acti_d12bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='masterservice',
            index=models.Index(fields=['price'], name='masters_mas_price_fd46ef_idx'),
        ),
    ]
