# Generated by Django 5.1.2 on 2026-10-08 18:59

import django.core.validators
import django.db.models.deletion
import masters.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service cities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=masters.models.master_avatar_upload_path),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='masters', to='masters.servicecategory'),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='masters_ser_slug_31a99a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active'], name='masters_ser_is_acti_ec3ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecity',
            index=models.Index(fields=['slug'], name='masters_ser_slug_be9853_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecity',
            index=models.Index(fields=['is_active'], name='masters_ser_is_acti_063ba5_idx'),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='masters', to='masters.servicecity'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['is_verified'], name='masters_mas_is_veri_d1bc68_idx'),
        ),
    ]
